services:
  api:
    container_name: cotacoes-api
    build: .               # usa o Dockerfile da raiz
    image: cotacoes-api:1.0
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      APP_SECURITY_AUTH_USERNAME: ${APP_SECURITY_AUTH_USERNAME}
      APP_SECURITY_AUTH_PASSWORD: ${APP_SECURITY_AUTH_PASSWORD}
      APP_SECURITY_JWT_ISSUER: ${APP_SECURITY_JWT_ISSUER}
      APP_SECURITY_JWT_EXPIRATION_MINUTES: ${APP_SECURITY_JWT_EXPIRATION_MINUTES}
      APP_SECURITY_JWT_SECRET: ${APP_SECURITY_JWT_SECRET}
    restart: unless-stopped
