spring:
  application:
    name: cotacoes

  datasource:
    url: jdbc:h2:mem:cotacoes-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080